### PR TITLE
Preserve indentation in indented here docs

### PR DESCRIPTION
**Pull request by trwyant**
This attempts to fix adamkennedy/PPI#251

### CODE REVIEW

**Comment by oalders** [comment]
I just tested this on some code with > 300 indented HEREDOCs and it fixed the issue for me.

**Comment by oalders** [comment]
I'm going to close and re-open this to try to trigger CI.

**Comment by oalders** [comment]
@haarg could you review this one?

**Comment by rafl** [comment]
That looks like a great improvement - thank you!

**Comment by oalders** [comment]
Thanks @trwyant, @rafl and @haarg!

**Pull request merged**
