### PR TITLE
Save some calls to refaddr

### PR DESCRIPTION
**Pull request by petdance**
This replaces #284.

### CODE REVIEW

**Comment by oalders** [comment]
I think you could have also just re-opened the closed PR, but this works too. 😄

**Comment by petdance** [comment]
I figured that if I deleted the branch it came from that the commits would disappear. That seems to not be the case. Oh well.

**Comment by oalders** [comment]
I'm going to close and re-open in order to kick off another build.

**Review by oalders — APPROVED** [review]

**Comment by oalders** [comment]
Thanks, @petdance!

**Pull request merged**
