### PR TITLE
Fix false-positive detection of Labels

### LINKED ISSUE #262: Misparse bareword as label
It is common to have barewords defined by, e.g. Glib:

`use Glib qw(TRUE FALSE);
`

When using a ternary operator, these can be misparsed. PPI 1.270 parses `TRUE :` as a label in the following:

`$result = $result_of_expression ? TRUE : FALSE;
`

instead of identifying the `:` as an operator.

### PR DESCRIPTION
**Pull request by h3xx**
Add regression tests for them too.
Update change log.

See fabe204067f01f9e93d9c6be762b5019d2a7b7c4 for examples.

Closes #262

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @h3xx! I'm going to close and re-open so that I can kick off a CI build.

**Comment by oalders** [comment]
We've got a test failure in the build.

**Comment by h3xx** [comment]
I think I fixed the test.

**Comment by h3xx** [comment]
Can you run the CI build again?

**Comment by oalders** [comment]
> Can you please run the CI build again?

Running now

**Comment by oalders** [comment]
This all looks good to me. I suspect that @wchristian would want the regression tests in the first commit added as `TODO` items and then have the `TODO` removed in the commit which introduces the fix. This would ensure that `git bisect` doesn't get broken by this PR.

**Comment by haarg** [comment]
The test counts are rather silly. No reason to remove them in this PR assuming it doesn't need any other changes, but if it does, replacing them with `done_testing` sounds like a good idea to me.

**Comment by h3xx** [comment]
> I suspect that @wchristian would want the regression tests in the first commit added as `TODO` items and then have the `TODO` removed in the commit which introduces the fix. This would ensure that git bisect doesn't get broken by this PR.

Updated.

Since I couldn't figure out how to mark a regression test code+dump file couplet as TODO, I simply reversed the *order* of the commits to fix first, THEN add tests. This ensures tests will pass for any given point in the repo history. :-)

**Comment by oalders** [comment]
@wchristian any concerns with this PR? It's essentially a 3 line change. I realize there may be more to consider, but the diff is not a heavy review. :)

**Comment by h3xx** [comment]
Updated: Fixed PR reference in changelog.

**Comment by wchristian** [comment]
oh yeah, and the changelog change, please amend that into the fix commit :D

**Comment by h3xx** [comment]
Okay, I think I understand. I updated my commits to:
1. Add my new tests under t/data/08_regression_todo, altering 08_regression.t to scan that directory
2. Fix the issue
3. Move my tests to t/data/08_regression.

I mimicked what I thought I saw passing in and out of `t/07_token.t` in the commit history. I think I even got the test count correct at all commits.

No change to the actual code at the head of my branch, just in the steps to getting there.

**Comment by wchristian** [comment]
Looks good to me, i'll be making a release with it tomorrow. I will in doing so also be squashing the latter two commits together, since the fix and un-todoing should be in the same commit, but if you wanna do it before i get to it, that'd be fine too. :)

**Comment by wchristian** [comment]
thanks a bunch!

merged and released as PPI-1.277

let's see what this release breaks :D

**Comment by wchristian** [comment]
Turns out this did indeed break something because Perl::Critic expected PPI to be broken. The relevant PR is here: https://github.com/Perl-Critic/Perl-Critic/pull/1048

**Comment by h3xx** [comment]
Relevant XKCD: https://xkcd.com/1172

**Comment by wchristian** [comment]
Haha, very appropriate. Sadly i didn't think of doing a dependent test until after the release. :)

**Pull request merged**
