### PR TITLE
Travis CI support

### PR DESCRIPTION
**Pull request by tsibley**
Testing on 5.6 through blead via Travis.  I fixed a number of problems with the tests, mostly regarding Perl 5.6, so that Travis would succeed.  You can see [the results for my fork](https://travis-ci.org/tsibley/PPI), but the repo owner (@adamkennedy) will need to flip the switch for Travis on the primary repo.

### CODE REVIEW

**Comment by moregan** [comment]
I believe that commits in this PR make redundant https://github.com/adamkennedy/PPI/pull/145

**Comment by tsibley** [comment]
Whoops. I should have known to look for patches first!

**Comment by oalders** [comment]
Thanks very much for your work @tsibley! I'm sorry that it never got merged. CI is now running on GitHub actions and Travis has not been great for a while now, so I'm going to close this.

**Comment by tsibley** [comment]
Hi @oalders! :wave: No worries, thanks for your note and for closing this (it's definitely irrelevant now). I hope all is well with you and yours.

**Comment by oalders** [comment]
Hi @tsibley. It's great to hear from you. Things are good here. I hope you and are yours are doing well too. It has been a long time since we all hung out at meta::hack. 😄

**Pull request closed without merging**
